repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^app/alembic/
      - id: end-of-file-fixer
        exclude: ^app/alembic/
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^app/alembic/
      - id: check-added-large-files
        exclude: ^app/alembic/

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        exclude: ^app/alembic/
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: ^app/alembic/

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
        exclude: ^app/alembic/
      - id: isort
        name: isort (cython)
        types: [cython]
        exclude: ^app/alembic/
      - id: isort
        name: isort (pyi)
        types: [pyi]
        exclude: ^app/alembic/

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^app/alembic/
        args:
          [
            "--per-file-ignores",
            "__init__.py:F401,F403",
            "--ignore",
            "E203,W503",
            "--max-line-length",
            "120",
          ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.3
    hooks:
      - id: uv-lock


  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit
        args: ["-c", "pyproject.toml"]
        description: "Bandit is a tool for finding common security issues in Python code"
        entry: bandit
        language: python
        language_version: python3
        types: [python]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^app/alembic/

  # - repo: https://github.com/hhatto/autopep8
  #   rev: v2.3.2
  #   hooks:
  #     - id: autopep8
  #       exclude: ^app/alembic/
  #       args: ["--in-place", "--max-line-length=120"]

  # Optional: Uncomment if needed
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - types-PyYAML
  #         - types-termcolor
  #         - types-Markdown
  #         - types-pytz
  #       files: "^ss_api/"
  #       pass_filenames: true
  #       exclude: ss_api/routes/reports/routes.py

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.3
  #   hooks:
  #     - id: python-safety-dependencies-check
  #       args: ["-i", "64459,64396,70612,71064,71199"]
