name: FastAPI CI with uv

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging
jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.22"

    - name: Create virtual environment and sync dependencies
      run: |
        uv venv .venv
        uv sync

    - name: Run pre-commit hooks with uv
      run: uv run pre-commit run --all-files

    - name: Run ruff linter check with uv
      run: uv run ruff check ./app

    - name: Start FastAPI app with uvicorn in background
      run: |
        uv run uvicorn app.main:app --host 127.0.0.1 --port 8001 &
        sleep 10 # wait for server startup

    - name: FastAPI boot smoke test
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8001 > uvicorn.log 2>&1 &
        for i in {1..20}; do
          curl -fSsf http://127.0.0.1:8001/api/health && break || sleep 1
        done
        cat uvicorn.log
        pkill -f "uvicorn main:app"
