name: FastAPI CI with uv

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging
jobs:
  test-and-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hbky
          POSTGRES_PASSWORD: my_secure_pass
          POSTGRES_DB: ci_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://hbky:my_secure_pass@localhost:5432/ci_db
      DATABASE_NAME: ci_db
      DATABASE_USER: hbky
      DATABASE_PASSWORD: my_secure_pass
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.22"

    - name: Create virtual environment and sync dependencies
      run: |
        uv venv .venv
        uv sync

    - name: Run pre-commit hooks with uv
      run: uv run pre-commit run --all-files

    - name: Run ruff linter check with uv
      run: uv run ruff check ./app

    - name: Start FastAPI app with uvicorn in background
      run: |
        uv run uvicorn app.main:app --host 127.0.0.1 --port 8001 &
        sleep 20 # wait for server startup

    - name: FastAPI boot smoke test
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8001 > uvicorn.log 2>&1 &
        for i in {1..20}; do
          curl -fSsf http://127.0.0.1:8001/api/health && break || sleep 1
        done
        cat uvicorn.log
        pkill -f "uvicorn main:app"
